# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11zZMjm-TIWfof6gZXg9TznY3U00zUB_-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
iris = load_iris()

X = iris.data
y = iris.target

print(X.shape)
print(y.shape)
X_train, X_test, y_train, y_test = train_test_split(
      X, y,
          test_size=0.2,
              random_state=42
              )
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
knn = KNeighborsClassifier(n_neighbors=3)

knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

print(y_pred)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
cm = confusion_matrix(y_test, y_pred)

print(cm)
print(classification_report(y_test, y_pred))
k_values = range(1, 21)
accuracies = []

for k in k_values:
    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)

    pred = model.predict(X_test)

    accuracies.append(
        accuracy_score(y_test, pred)
    )

print(accuracies)
plt.figure(figsize=(8,5))

plt.plot(k_values, accuracies, marker='o')

plt.title("K Value vs Accuracy")
plt.xlabel("K")
plt.ylabel("Accuracy")

plt.grid(True)
plt.show()
from matplotlib.colors import ListedColormap

X = iris.data[:, :2]
y = iris.target

scaler = StandardScaler()
X = scaler.fit_transform(X)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y)

h = 0.02

x_min, x_max = X[:,0].min()-1, X[:,0].max()+1
y_min, y_max = X[:,1].min()-1, X[:,1].max()+1

xx, yy = np.meshgrid(
    np.arange(x_min, x_max, h),
    np.arange(y_min, y_max, h)
)

Z = knn.predict(
    np.c_[xx.ravel(), yy.ravel()]
)

Z = Z.reshape(xx.shape)

plt.figure(figsize=(8,6))

plt.contourf(xx, yy, Z, alpha=0.3)

plt.scatter(
    X[:,0],
    X[:,1],
    c=y,
    edgecolor='k'
)

plt.title("KNN Decision Boundary")
plt.show()